# Generated by Django 5.2.12 on 2026-03-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('win1', models.FloatField(default=1.0)),
                ('draw', models.FloatField(default=1.0)),
                ('win2', models.FloatField(default=1.0)),
                ('double_1x', models.FloatField(default=1.0)),
                ('double_12', models.FloatField(default=1.0)),
                ('double_x2', models.FloatField(default=1.0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
