# Generated by Django 5.2.12 on 2026-03-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('bet_amount', models.FloatField()),
                ('total_odds', models.FloatField()),
                ('potential_win', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_dashboard.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(max_length=20)),
                ('odds', models.FloatField()),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_dashboard.bet')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_dashboard.game')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='games',
            field=models.ManyToManyField(through='bot_dashboard.BetSelection', to='bot_dashboard.game'),
        ),
    ]
