# Generated by Django 5.2.12 on 2026-03-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0003_bet_betselection_bet_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='bet',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='betselection',
            name='match_info',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='double_12',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='double_1x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='double_x2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='draw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='team1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='team2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='win1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='win2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
