# Generated by Django 5.2.12 on 2026-03-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0004_remove_userprofile_created_at_bet_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='score_team1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='score_team2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
