# Generated by Django 5.2.12 on 2026-03-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0006_chapapayment_alter_userprofile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='betselection',
            name='match_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
