# Generated by Django 5.2.12 on 2026-03-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0007_betselection_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
