# Generated by Django 5.2.12 on 2026-03-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0008_bet_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('telegram_id', models.BigIntegerField()),
                ('amount', models.FloatField()),
                ('method', models.CharField(choices=[('telebirr', 'Telebirr'), ('mpesa', 'M-Pesa'), ('cbe_birr', 'CBE Birr')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
