# Generated by Django 5.2.12 on 2026-03-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0009_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='country',
            field=models.CharField(choices=[('england', 'England'), ('germany', 'Germany'), ('spain', 'Spain'), ('italy', 'Italy'), ('russia', 'Russia'), ('france', 'France'), ('netherlands', 'Netherlands'), ('portugal', 'Portugal'), ('switzerland', 'Switzerland'), ('saudi_arabia', 'Saudi Arabia'), ('ethiopia', 'Ethiopia'), ('scotland', 'Scotland'), ('ukraine', 'Ukraine'), ('south_africa', 'South Africa')], default='england', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='country_flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
