# Generated by Django 5.2.12 on 2026-03-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0010_game_country_game_country_flag_game_game_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bonus',
            field=models.FloatField(default=10),
        ),
    ]
