# Generated by Django 5.2.12 on 2026-03-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0011_alter_userprofile_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapapayment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
