# Generated by Django 5.2.12 on 2026-03-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0012_chapapayment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('amharic', 'Amharic')], default='english', max_length=10),
        ),
    ]
