# Generated by Django 5.2.12 on 2026-03-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0013_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='wallet_used',
            field=models.CharField(choices=[('balance', 'Balance Wallet'), ('bonus', 'Bonus Wallet')], default='balance', max_length=10),
        ),
    ]
