# Generated by Django 5.2.12 on 2026-03-18 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0015_alter_game_double_12_alter_game_double_1x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_number', models.IntegerField()),
                ('numbers', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_dashboard.userprofile')),
            ],
            options={
                'unique_together': {('user', 'clicked_number')},
            },
        ),
    ]
