# Generated by Django 5.2.12 on 2026-03-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0017_bingonumberpick'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bingocard',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bingonumberpick',
            name='picked_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_dashboard.userprofile'),
        ),
        migrations.CreateModel(
            name='BingoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=32, unique=True)),
                ('drawn_numbers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_dashboard.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BingoParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_number', models.IntegerField()),
                ('card_numbers', models.JSONField(blank=True, default=list)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_dashboard.bingogame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_dashboard.userprofile')),
            ],
        ),
    ]
