# Generated by Django 5.2.12 on 2026-03-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0019_bingocardtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingoparticipant',
            name='clicked_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='BingoCard',
        ),
    ]
