# Generated by Django 5.2.12 on 2026-03-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0020_alter_bingoparticipant_clicked_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingoparticipant',
            name='clicked_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
