# Generated by Django 5.2.12 on 2026-03-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0021_alter_bingoparticipant_clicked_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingogame',
            name='timer_seconds',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='bingogame',
            name='timer_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
