# Generated by Django 5.2.12 on 2026-03-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0022_bingogame_timer_seconds_bingogame_timer_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingoparticipant',
            name='clicked_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bingoparticipant',
            unique_together={('game', 'clicked_number')},
        ),
    ]
