# Generated by Django 5.2.12 on 2026-03-20 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0023_alter_bingoparticipant_clicked_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hold_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='bot_dashboard.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
