# Generated by Django 5.2.12 on 2026-03-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0024_userprofile_hold_balance_withdrawal_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingogame',
            name='timer_seconds',
            field=models.IntegerField(default=90),
        ),
        migrations.CreateModel(
            name='DamaGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=32, unique=True)),
                ('bet_amount', models.FloatField()),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('board', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dama_player1', to='bot_dashboard.userprofile')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dama_player2', to='bot_dashboard.userprofile')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_dashboard.userprofile')),
            ],
        ),
    ]
