# Generated by Django 5.2.12 on 2026-03-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0025_alter_bingogame_timer_seconds_damagame'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_home', models.CharField(max_length=100)),
                ('team_away', models.CharField(max_length=100)),
                ('score_home_team', models.PositiveIntegerField(blank=True, null=True)),
                ('score_away_team', models.PositiveIntegerField(blank=True, null=True)),
                ('match_time', models.DateTimeField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
