# Generated by Django 5.2.12 on 2026-03-23 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0027_jackpot_guessgame_jackpot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jackpot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='jackpot',
            name='entry_fee',
        ),
        migrations.RemoveField(
            model_name='jackpot',
            name='jackpot_id',
        ),
        migrations.RemoveField(
            model_name='jackpot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='jackpot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jackpot',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('finished', 'Finished')], default='inactive', max_length=20),
        ),
        migrations.CreateModel(
            name='JackpotBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField()),
                ('selections', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jackpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_dashboard.jackpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_dashboard.userprofile')),
            ],
        ),
    ]
