# Generated by Django 5.2.12 on 2026-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0028_remove_jackpot_end_time_remove_jackpot_entry_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackpot',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jackpot',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
