# Generated by Django 5.2.12 on 2026-03-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0029_jackpot_end_time_jackpot_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackpot',
            name='jackpot_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
