# Generated by Django 5.2.12 on 2026-03-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0030_jackpot_jackpot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackpotbet',
            name='telegram_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
