# Generated by Django 5.2.12 on 2026-03-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0031_jackpotbet_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackpotbet',
            name='bet_id',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
