# Generated by Django 5.2.12 on 2026-03-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0032_jackpotbet_bet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackpot',
            name='entry_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='jackpot',
            name='total_win',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
